language: cpp

compiler:
  - gcc
  - clang

before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -qq
 - wget http://sourceforge.net/projects/boost/files/boost/1.58.0/boost_1_58_0.tar.bz2/download -O /tmp/boost.tar.bz2
 - tar jxf /tmp/boost.tar.bz2
 - mv boost_1_58_0 $PWD/boost-trunk
 - export BOOST_ROOT="$PWD/boost-trunk"
 - cd $BOOST_ROOT
 - ./bootstrap.sh
 - cd $TRAVIS_BUILD_DIR

install:
  - sudo apt-get install -qq gcc-4.8 g++-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - if [[ ${CC} = gcc ]]; then
      wget http://downloads.sourceforge.net/ltp/lcov-1.11.tar.gz &&
      tar xvfz lcov-1.11.tar.gz &&
      sudo make -C lcov-1.11 install &&
      rm -rf lcov-1.11.tar.gz lcov-1.11 &&
      sudo cp -v `which gcov-4.8` `which gcov`;
    fi

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - make unit
  - if [[ ${CC} = gcc ]]; then
      make coverage;
    fi
  - make test

after_success:
  - if [[ ${CC} = gcc ]]; then
      bash <(curl -s https://codecov.io/bash);
    fi

os:
  - linux
