# We deals with C++
language: cpp

# Setup the test matrix
matrix:
  include:
    - compiler: gcc
      os: linux
      env: TOOLSET=g++-4.8
    - compiler: gcc
      os: linux
      env: TOOLSET=g++-4.9
    - compiler: gcc
      os: linux
      env: TOOLSET=g++-5
    - compiler: clang
      os: linux
      env: TOOLSET=clang++

# Install all dependencies
before_install:
# Get packages
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:h-rayflood/llvm
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-4.8 g++-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - bash ./script/travis/install.sh
  - export BOOST_ROOT="$HOME/boost-trunk"

# Prepare build
before_script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_CXX_COMPILER=$TOOLSET

# Build unit and run test
script:
  - make unit
  - make coverage
  - if [[ ${CC} = gcc ]]; then make coverage; fi
  - make test

after_success:
  - if [[ ${CC} = gcc ]]; then bash <(curl -s https://codecov.io/bash); fi
